# Generated by Django 3.0.5 on 2020-05-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_img_url',
            field=models.CharField(max_length=300),
        ),
    ]
