# Generated by Django 3.0.6 on 2020-06-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_admin', '0002_auto_20200528_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtags',
            name='text',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
