name: master

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: Run coverage test
      run: |
        bash <(curl -s https://codecov.io/bash)

  security-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: PyCharm Python Security Scanner
      uses: tonybaloney/pycharm-security@1.16.0